files:
  "/etc/nginx/conf.d/00_elastic_beanstalk_laravel.conf":
    mode: "000644"
    owner: root
    group: root
    content: |
      location / {
          root /var/www/html/my-laravel-app/public;
          index index.php index.html index.htm;
          try_files $uri $uri/ /index.php?$query_string;
      }

container_commands:
  01_composer_install:
    command: "composer install --no-dev --optimize-autoloader"
    cwd: "/var/www/html/my-laravel-app"

  02_artisan_migrate:
    command: "php artisan migrate --force"
    cwd: "/var/www/html/my-laravel-app"

  03_artisan_storage_link:
    command: "php artisan storage:link"
    cwd: "/var/www/html/my-laravel-app"

  04_reload_nginx:
    command: "sudo service nginx reload"
